### ISSUE TITLE
parse path parameters in awsSchema.Event

### ISSUE THREAD

**Issue by pinnareet** [thanakijwanavit/awsSchema#1]
i would like a function to parse path parameters for urls like /van/{id}

it can be accessed from event['pathParameters'], so for the above example

the template
```yaml
Events:
  GetApi:
    Type: Api 
    Properties:
      Path: /van/{id}
       Method: get
      RestApiId: !Ref VansApi
``` 
```python
event['pathParameters'] = {'id': value}
```
